# This file was generated by liblab | https://liblab.com/

from pinnacle_link import PinnacleLink, Environment

sdk = PinnacleLink(
    username="YOUR_USERNAME",
    password="YOUR_PASSWORD",
    base_url=Environment.DEFAULT.value,
)

result = sdk.others.sports_v2_get()

print(result)
